# Generated by Django 4.2.11 on 2024-05-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
    ]
