services:
  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'  # Use port 3307 on the host to avoid port conflict
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-ppassword", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mydb:/var/lib/mysql
    networks:
      - backend-network
  
  backend:
    image: semanticflix_backend
    build: 
      context: ./backend/project
      dockerfile: Dockerfile
    container_name: semanticflix_backend
    command: sh -c "python backend/project/manage.py migrate --noinput && python backend/project/manage.py collectstatic --noinput && python backend/project/manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8020:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://db:3306 || exit 1"]
      interval: 30s
      retries: 10
    networks:
    - backend-network

networks:
  backend-network:
    driver: bridge