version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c 'python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000'
    restart: always
    environment:
      MYSQL_HOST: 'mysql-db'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - .:/backend
    ports:
      - '8000:8000'
    depends_on:
      - mysql-db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  my-db:
  backend: