import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        alignItems:"center",
        justifyContent:"center",
        flex:1,
        padding:"5%",
        backgroundColor:"white",
    },
    top_container:{
        alignItems:"center",
        justifyContent:"center",
        flex:1,
        minWidth:"100%",
        maxWidth:"100%",
   
    },
    welcome:{
        fontWeight:"bold",
        fontSize:30,
        color:"black",
    },
    mid_container:{
        alignItems:"center",
        flex:0.1,
    },
    bottom_container:{
        alignItems:"center",
        justifyContent:"center",
        flex:1,

    },
    username_input_box:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:1,
        borderRadius:10,
        shadowColor:'black',
        shadowRadius: 5,
        minWidth:"100%",
        margin:"2%",
    },
    icon_box:{
        padding:"2%",
        marginRight:"1%",
    },
    password_input_box:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:1,
        borderRadius:10,
        shadowColor:'black',
        shadowRadius: 5,
        minWidth:"100%",
        marginBottom:"2%",
        margin:"2%",
    },
    chpass_view:{
        alignItems:"flex-start",
        justifyContent:"flex-end",
        flexDirection:"row",
        borderRadius:10,
        minWidth:"100%",
    },
    chpass_button:{
        alignItems:"flex-end",
        justifyContent:"flex-end",
        marginBottom:"3%",
        padding:"1%",
    },
    chpass_text:{
        fontWeight:"bold",
        fontSize:16,
        color:"black",
    },
    login_view:{
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#DC143C",
        minWidth:"100%",
        padding:"2%",
        borderRadius:10,
        marginBottom:"3%",

    },
    login_button:{
        alignItems:"center",
        justifyContent:"center",
        minWidth:"100%",
        padding:"3%",
        borderRadius:10,
    },
    login_text:{
        fontWeight:"bold",
        color:"white",
        fontSize:18,
    },
    input_text:{
        fontWeight:"bold"
    },
    signup_view:{
        alignItems:"stretch",
        justifyContent:"space-between",
        flexDirection:"row",
        minWidth:"100%",
        padding:"1%",
        borderRadius:10,
        marginBottom:"3%",
    },
    signup_text:{
        fontWeight:"bold",
        fontSize:16,
        color:"black",
    },
    
})