name: "Issue"
description: "Somethings have to be done"
title: "Do something please"
labels: ["research", "priority: medium", "workload: 2", "issue template"]
assignees: []
projects: ["bounswe/70"]
body:
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: Provide a description of the task
      value: "You need to do this, do that..."
  - type: textarea
    id: required-changes
    attributes:
      label: Required Activities
      description: Provide detailed information about the necessary changes/activities
      value: |
        - [XX](url)
        - [XX](url)
  - type: input
    id: estimated-time
    attributes:
      label: Estimated Time
      description: How many hours are needed for this issue
      placeholder: ex. 2, 0.5, 1, 10
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: When is the deadline for this issue
      placeholder: ex. 01 Feb 2001
  - type: input
    id: reviewer
    attributes:
      label: Reviewer
      description: Who will review this issue
      placeholder: ex. @danzio
