name: Wiki Revision
description: Certain sections of Wiki need to be revised
title: "[Wiki Revision] XX"
labels: ["wiki", "priority: medium", "workload: 2", "issue template"]
assignees: []
projects: ["bounswe/36"]
body:
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: Provide a description of the task
      value: "We need to update several wiki pages for our project. The pages and required changes are listed below."
  - type: textarea
    id: changing-sections
    attributes: 
      label: Sections to be Revised
      description: List of sections to be revised
      value: |
        - [PageXX](page-revision-link-xx)
        - [PageXX](page-revision-link-xx)
        - Non-Page-Section-XX
  
  - type: textarea
    id: required-changes
    attributes: 
      label: Required Changes
      description: Provide detailed information about the required changes
      value: |
        - XX Communication plan needs an extra section for extra meetings 
        - XX The Home page of the wiki needs another section for weekly contributions
        - XX Change meeting notes order in the sidebar to oldest first  
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List of acceptance criteria
      options:
        - label: Changes are made and visible
        - label: Changes are reviewed by the reviewer
  - type: input
    id: reviewer
    attributes:
      label: Reviewer
      description: Who will review this task
      placeholder: link username with '@', ex. @Halil-Ibrahim-Kasapoglu
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: When is the deadline for this task
      placeholder: ex. 01 Feb 2001
