version: '3.7'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'  # Use port 3307 on the host to avoid port conflict
    volumes:
      - ./mydb:/var/lib/mysql
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: semanticflix_backend
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8019:8000"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3307 || exit 1"]
      interval: 30s
      retries: 10
volumes:
  data: 