# Generated by Django 4.2 on 2024-11-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
