# Generated by Django 4.2 on 2024-11-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketfeed', '0002_alter_portfolio_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
