# Generated by Django 4.2 on 2024-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketfeed', '0003_stock_last_price_stock_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stocks', models.ManyToManyField(to='marketfeed.stock', verbose_name='list of stocks in the index')),
            ],
        ),
    ]
