# Generated by Django 4.2 on 2024-12-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketfeed", "0005_index_currency_index_symbol"),
        ("marketfeed", "0005_portfolio_stocks"),
    ]

    operations = []
