# Generated by Django 4.2 on 2024-12-13 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketfeed", "0007_portfoliostock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="disliked_by",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
