# Generated by Django 4.2 on 2024-11-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_badge_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
