# Generated by Django 4.2.11 on 2024-05-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
