@startuml
left to right direction
skinparam packageStyle rect
skinparam actor {
    BackgroundColor PaleGreen
    BorderColor DarkGreen
}

package Users{

actor RegisteredUser as U
actor Guest as G

}

actor Admin as A



package Posts {
  (Comment On Posts) as COP
  (Unlike Post) as UP
  (          Create Film Lists          ) as CFL
  (Rate Films) as RF
  (       Follow User       ) as FU 
  (Like Post) as LP
  A --> (         Create Posts         )
  U --> (Create Posts)
  U --> (RF)
  U --> (LP)
  U --> (FU)
  A --> (RF)
  

}
package Administrative{
  A --> (Add Films)
  A --> (Remove Films)

}

package Browse/View{
(View Followers) as VF
(Remove Follower) as RF
(View User Profiles) as VU
(View Film Lists) as VFL
(Search Users) as SU
(Search_films) as SF
(Search Film Lists) as SFL
U --> (View Films)
U --> (RF)
U --> (VF)
U --> (VU)

G --> (View Films)

U --> (SF)
G --> (SF)
A --> (SF)
(Browse Popular Films) as BPF
(Browse Recently Released Films) as BRRF
U --> (BRRF)
G --> (BRRF)
A --> (BRRF)
U --> (BPF)
G --> (BPF)
A --> (BPF)
}

package Edit/Update/Delete {
(Edit Film Lists) as EFL
(Delete Owned Film Lists) as DOFL
(Edit Owned Profile) as EO  
(Edit EVERY Profile) as EE
U --> EO
A --> (EE)
(Edit Owned Post) as EOP
(Edit EVERY Post) as EEP
U --> (EOP)
A --> (EEP)
(Delete Owned Post) as DOP
(Delete EVERY Post) as DEP
U --> (DOP)
A --> (DEP)

}

package Authentication{
  (Accept Privacy Policy) as APP
  (Verify Mail) as VM 
  U --> (Login)
  U --> (Logout)
  A --> (Login)
  A --> (Logout)
  G --> (Register)
  (Change/Forgot Password) as CP
  A --> (CP)
  U --> (CP)
  G --> (CP)
  (Register) "1" *-- "1" (APP) : includes
  (Register) "1" *-- "1" (VM) : includes
}




@enduml