@startuml
left to right direction
skinparam packageStyle rect
skinparam actor {
    BackgroundColor PaleGreen
    BorderColor DarkGreen
}

package Users{

actor RegisteredUser as U
actor Guest as G

}

actor Admin as A



package Posts {
  A --> (Create Posts)
  U --> (Create Posts)
  U --> (Rate Films)
  A --> (Rate Films)

}
package Administrative{
  A --> (Add Films)
  A --> (Remove Films)

}

package BrowseandView{
U --> (View Films)
G --> (View Films)
(Searchfilms) as SF

}


U --> (Edit Profile)


package Authentication{
U --> (Login)
U --> (Logout)
A --> (Login)
A --> (Logout)
G --> (Register)
}




@enduml
